---
- name: Configurar data e hora
  hosts: all
  become: yes

  tasks:

    - name: Definir timezone
      timezone:
        name: America/Sao_Paulo

    - name: Garantir NTP ativo
      command: timedatectl set-ntp true
      changed_when: false

    - name: Habilitar systemd-timesyncd
      systemd:
        name: systemd-timesyncd
        enabled: yes
        state: started

    - name: Reiniciar serviço de sincronização
      systemd:
        name: systemd-timesyncd
        state: restarted

    - name: Ver status do tempo
      command: timedatectl status
      register: time_status

    - name: Mostrar status
      debug:
        var: time_status.stdout_lines